In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
from PIL import Image
import NeuralNetworkClasses as nn
import FHmodules as fh
import os


# Image stuff:

In [ ]:
img = Image.open('testdigit9.bmp').convert('L')
img.size

In [ ]:
imgArr = np.array(img)
imgArr

In [ ]:
imgArr.shape

In [ ]:
bwArr = np.where(imgArr == 255, 0,1)
bwArr

In [ ]:
df = pd.DataFrame(bwArr)

In [ ]:
df

In [10]:


print(os.getcwd())
os.chdir("C:/Users/camer/Desktop/Cam's cython crojects/Digit Recognition")
print(os.getcwd())

files, paths, labels = fh.getFileList('Digits Test Folder',"C:/Users/camer/Desktop/Cam's cython crojects/Digit Recognition")

c:\Users\camer\Desktop\Cam's cython crojects\Digit Recognition
C:\Users\camer\Desktop\Cam's cython crojects\Digit Recognition


In [11]:
files, paths, labels = fh.getFileList('Digits Test Folder',"C:/Users/camer/Desktop/Cam's cython crojects/Digit Recognition")

In [12]:
for i in range(0,len(files)):
    print(files[i])
    print(paths[i])
    print(labels[i])

0_testdigit.bmp
C:/Users/camer/Desktop/Cam's cython crojects/Digit Recognition/Digits Test Folder/0_testdigit.bmp
0
1_testdigit.bmp
C:/Users/camer/Desktop/Cam's cython crojects/Digit Recognition/Digits Test Folder/1_testdigit.bmp
1
2_testdigit.bmp
C:/Users/camer/Desktop/Cam's cython crojects/Digit Recognition/Digits Test Folder/2_testdigit.bmp
2
3_testdigit.bmp
C:/Users/camer/Desktop/Cam's cython crojects/Digit Recognition/Digits Test Folder/3_testdigit.bmp
3
4_testdigit.bmp
C:/Users/camer/Desktop/Cam's cython crojects/Digit Recognition/Digits Test Folder/4_testdigit.bmp
4
5_testdigit.bmp
C:/Users/camer/Desktop/Cam's cython crojects/Digit Recognition/Digits Test Folder/5_testdigit.bmp
5
6_testdigit.bmp
C:/Users/camer/Desktop/Cam's cython crojects/Digit Recognition/Digits Test Folder/6_testdigit.bmp
6
7_testdigit.bmp
C:/Users/camer/Desktop/Cam's cython crojects/Digit Recognition/Digits Test Folder/7_testdigit.bmp
7
8_testdigit.bmp
C:/Users/camer/Desktop/Cam's cython crojects/Digit Recog

In [13]:
for file in paths:
    df = fh.imgToDataframe(file)
    print(df.sum().sum())

531
7865
17049
20542
19087
18235
15329
17370
25599
10770


# ML stuff:

In [2]:
sizes = [10,5,2]
funcs = [nn.relu,nn.sigmoid,nn.identity]

testnet = nn.Net(sizes,funcs)

In [ ]:
np.matmul([1,2,3,4,5,6,7,8,9,10],testnet.weights[0])
#testnet.weights

In [3]:
trialdata = np.array([-1,1,-1,1,-1,1,-1,1,-1,1])

In [ ]:
print(testnet.layerlist[0].activation(trialdata))

In [ ]:
testnet.zero()

In [4]:
testnet.forward(trialdata)

[-1  1 -1  1 -1  1 -1  1 -1  1]
[1 1 1 1 1]
[1 1 1 1 1]
[0.99752738 0.99752738]


In [ ]:
testnet.out

In [5]:
testnet.getParams()

([10, 5, 2],
 [<function NeuralNetworkClasses.relu(x)>,
  <function NeuralNetworkClasses.sigmoid(x)>,
  <function NeuralNetworkClasses.identity(x)>],
 [array([[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]),
  array([[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]])])

In [9]:
a = nn.Net(testnet.params[0],testnet.params[1],testnet.params[2],testnet.params[3])

# Pooling test:

In [73]:
files, paths, labels = fh.getFileList('Digits Test Folder',"C:/Users/camer/Desktop/Cam's cython crojects/Digit Recognition")

In [74]:

df = fh.imgToDataframe(paths[4])

In [75]:
df

0   1   2   3   4   5   6   7   8   9   ...  90  91  92  93  94  95  96  \
0    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
3    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
4    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
95   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
96   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
97   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
98   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
99   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   

    97  98  99  
0    0   0   0  
1    0   0   0  
2    0   0   0  
3    0   0   0  
4    0   0   0  
..  ..  ..  ..  
95   0   0   0  
96   0   0   0  
97   0   0   0  
98   0   0   0  
99   0   0   0  

[100 rows x 100 columns]

In [76]:
poolArr = df.to_numpy()

In [89]:
pooling_sample_size = 4
newArr = np.empty((int((poolArr[0].size)/pooling_sample_size), int((poolArr[1].size)/pooling_sample_size)))


for x in range(0,len(poolArr) -1,pooling_sample_size):
    for y in range(0,len(poolArr[0]) -1,pooling_sample_size):
        vals = []
        for i in range(0,pooling_sample_size):
            for j in range(0,pooling_sample_size):
                vals.append(poolArr[x+i][y+j])
        
        xindex = int(np.floor(x/pooling_sample_size))
        yindex = int(np.floor(y/pooling_sample_size))
        newArr[xindex][yindex] = int(np.mean(vals))

#poolout = Image.fromarray(newArr)
#poolout.convert('L')


In [81]:
newArr.size

625

In [90]:
sizes = [newArr.size,300,20,10]
funcs = [nn.sigmoid,nn.relu,nn.relu,nn.identity]

imgNet = nn.Net(sizes,funcs)

In [91]:
imgNet.forward(newArr.flatten())

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.